apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: site
  labels:
    app: site
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: site
  minReplicas: {{ .Values.minReplicas }}
  maxReplicas: {{ .Values.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
