apiVersion: v1
kind: Service
metadata:
  name: site
  labels:
    app: site
spec:
  type: NodePort
  selector:
    app: site
  ports:
    - protocol: TCP
      port: {{ .Values.appPort }}
      targetPort: {{ .Values.appPort }}
